[workspace]
resolver = "2"

members = ["crates/api"]

[workspace.dependencies]
tokio = { version = "1.44.2", features = ["full"] }
tokio-async = "1.44.2"
serde = "1.0.217"
serde_json = "1.0.138"
dotenvy = "0.15.7"
chrono = { version = "=0.4.40", features = ["clock", "serde"] }
anyhow = "1.0.95"
thiserror = "2.0.11"
once_cell = "1.20.3"
clap = "4.5.31"
async-trait = "0.1.83"
bcs = "0.1.6"
url = "2.5.4"
tokio-util = "0.7.13"
futures = "0.3.31"
axum = "0.8.3"
tempfile = "3.19.1"
tower-http = "0.6.2"
wait-timeout = "0.2.1"
